# Generated by Django 4.0.4 on 2022-05-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='typeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('complexity', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(db_index=True, max_length=500)),
                ('answer', models.CharField(db_index=True, max_length=50)),
                ('image', models.ImageField(blank=True, db_index=True, null=True, upload_to='images/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.typetask')),
            ],
        ),
    ]
