# Generated by Django 4.0.4 on 2022-05-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetask',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
