# Generated by Django 4.0.4 on 2022-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_task_answer_alter_task_content_alter_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
