# Generated by Django 4.0.4 on 2022-05-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_typetask_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetask',
            name='complexity',
            field=models.CharField(choices=[('easy', 'Легко'), ('middle', 'Средне'), ('hard', 'Тяжело')], max_length=10),
        ),
    ]
