# Generated by Django 4.0.4 on 2022-05-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_subtype_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtype',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
