# Generated by Django 4.0.4 on 2022-05-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_subtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dop',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
