# Generated by Django 4.0.4 on 2022-05-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_task_dop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dop',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
