# Generated by Django 4.0.4 on 2022-06-01 08:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_task_dop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dop',
            field=tinymce.models.HTMLField(),
        ),
    ]
