# Generated by Django 4.0.4 on 2022-06-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_task_dop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dop',
            field=models.TextField(max_length=3000),
        ),
    ]
