# Generated by Django 4.0.4 on 2022-06-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_task_dop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dop',
        ),
    ]
