# Generated by Django 4.0.4 on 2022-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_task_dop'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='solution',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
