# Generated by Django 4.0.4 on 2022-06-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_task_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='solution',
            field=models.TextField(blank=True, default='Рещение ещё не добавили (', max_length=500),
        ),
    ]
