# Generated by Django 4.0.4 on 2022-06-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_task_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=10000)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.subtype')),
            ],
        ),
    ]
