# Generated by Django 4.0.4 on 2022-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_decision_type_advuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='pro',
            field=models.BooleanField(default=False),
        ),
    ]
