# Generated by Django 4.0.4 on 2022-06-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_profile_delete_advuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='static/avatar.jpg', upload_to=''),
        ),
    ]
