# Generated by Django 4.0.4 on 2022-06-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='home.task'),
        ),
    ]
