# Generated by Django 4.0.4 on 2022-06-24 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
