# Generated by Django 4.0.4 on 2022-06-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_profile_tasks_profile_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
